### ISSUE TITLE
Tag versions shipped with VS

### ISSUE THREAD

**Issue by SamB** [microsoft/CMake#105]
To aid in troubleshooting, it would be helpful if every version shipped with Visual Studio was tagged in the repository.

I'm honestly not sure if it would be a good idea to provide binaries or not, but it would presumably be easier not to do that.

**Comment by kuchungmsft** [comment]
Thanks for your suggestion. We have updated our pipeline to tag the shipped version.

![image](https://user-images.githubusercontent.com/105310954/169581307-b28306fd-f156-41f9-bbad-501f37f40873.png)
