### ISSUE TITLE
Add C# Support

### ISSUE THREAD

**Issue by awakecoding** [microsoft/CMake#16]
I know this is not a tiny feature to add, but I've been wanting it for years. I highly appreciate that Microsoft worked on providing proper CMake support for the Universal Windows Platform. I am now wondering, would it be possible to consider adding proper C# support as well? Please share your thoughts on the matter, I would be very interested in such a feature.

**Comment by micst** [comment]
It's always worth monitoring the official mailing lists:

https://cmake.org/pipermail/cmake-developers/2016-February/027750.html

https://cmake.org/pipermail/cmake-developers/2016-February/027836.html

In short: there is C# support but it will take some time until it gets integrated into upstream cmake. If you are eager to try it out, check the "csharp" branch here:

https://github.com/micst/CMake/tree/csharp

**Comment by awakecoding** [comment]
@micst I was not aware of these recent developments, I will definitely follow this! Thanks a lot :)

**Comment by micst** [comment]
@awakecoding yeah, it's pretty new, I know ;-). But it's great to hear some people are interested in it!

**Comment by micst** [comment]
With commit f6e4602fe7467fe149f3843a3263a986ea1d804d C# support for cmake has been merged to upstream master branch. This means **CMake 3.8.0** will support generation of ``.csproj`` files for Visual Studio generators 2010 and newer. I believe this closes this issue.

**Comment by awakecoding** [comment]
@micst I look forward to it! Thanks :)

**Comment by khouzam** [comment]
Great to see it merged in.
