### ISSUE TITLE
VS toolset upgrade

### ISSUE THREAD

**Issue by EvgenyAgafonchikov** [microsoft/CMake#2]
After running of the following command:

```
bin> ..\..\CMake\bin\bin\Release\cmake.exe -G "Visual Studio 14 2015 Win64" -DCMAKE_SYSTEM_NAME:String=WindowsStore -DCMAKE_SYSTEM_VERSION:String="8.1" -DCMAKE_VS_EFFECTIVE_PLATFORMS:String=x64 -DCMAKE_INSTALL_PREFIX:PATH=C:\Users\install ..
```

and opening the resulting solution VS2015 suggests to upgrade CMake-related projects only (e. g. ALL_BUILD, INSTALL, etc.) others are still using vc120 toolset instead of vc140

**Comment by khouzam** [comment]
The CMake projects are building Utility projects (not store or phone projects) so the toolset is not critical.
I've tried either way and the projects don't have issues.
