### ISSUE TITLE
VCMDDAndroid for VS 2017 

### ISSUE THREAD

**Issue by BattleShipPark** [microsoft/CMake#25]
I'm trying https://blogs.msdn.microsoft.com/vcblog/2015/12/15/support-for-android-cmake-projects-in-visual-studio/, but you support only until VS 2015. When I installed VS 2017 your cmake says:

CMake Error in CMakeLists.txt:
  CMAKE_SYSTEM_NAME is 'VCMDDAndroid' but 'Visual C++ for Mobile Development
  (Android support)' is not installed.

You can support VS 2017? Or can you do it?

Thanks.

**Comment by bodong1987** [comment]
who know how to add vs2017 support ?

**Comment by jgoshi** [comment]
When you install VS 2017 you need to select the "Mobile development with C++" workload. If you run the Visual Studio Installer you can check if that workload was selected, and if not you can add it.

Once that is installed, you can open the generated project file in VS 2017 (if it asks you to upgrade say no). Generator support is only available for 2015 so you cannot generate the project for 2017, but VS 2017 will be able to open and build the project files.

**Comment by rcdailey** [comment]
Is VCMDDAndroid still not merged to upstream CMake? That's a shame; last commit on that branch was from 2016. Really need to officially support Android cross compilation in Visual Studio via CMake! If this is already possible and I'm missing something, please let me know. But right now [the original blog article](https://blogs.msdn.microsoft.com/vcblog/2015/12/15/support-for-android-cmake-projects-in-visual-studio/) seems very very out of date now.

**Comment by greazer** [comment]
@rcdailey, No it is not merged, and that has been an intentional decision. We are currently in the process of re-evaluating how we improve Android support in VS.

**Comment by NukeBird** [comment]
So, how everything going? 

It's pity that here is no VS2017 support

**Comment by jgoshi** [comment]
Closing this issue as this will not be done for VS2017, and we currently have no plans to add this support.
