### ISSUE TITLE
Generation fails for Windows Universal after VS 2015 update.

### ISSUE THREAD

**Issue by Umkerius** [microsoft/CMake#5]
Hi! 
I updated Visual Studio 2015 RC to release version (and Win10 SDK too) and cmake now fails to generate projects for WindowsStore == 10.0.
I compared old generated (with RC) project and project from release VS project templates. I found a few different places: 'ApplicationTypeRevision' in release is 10.0 (vs old 8.2). 'WindowsTargetPlatformVersion' and 'WindowsTargetPlatformMinVersion' fields in old project are missed.
I'll try to fix this issues and write about result.

**Comment by khouzam** [comment]
Hi Umkerius,

Thanks for reporting this. I have just pushed an update that addresses these issues. You should be able to properly build now. If now, please tell me.

**Comment by Umkerius** [comment]
Hi, Gilles!
It's works! Thank you.
