### ISSUE TITLE
CMakeSettings.json: cmakeExecutable only working for remote machines

### ISSUE THREAD

**Issue by sebastue** [microsoft/CMake#52]
The property 'cmakeExecutable' is only working for remote machines. 
As an user I want to define my own cmake version even on the local machine, because I want a newer version or I want to use my own settings.
The property 'cmakeExecutable' should also work for the local machine.

Microsoft Visual Studio Professional 2017 Preview
Version 15.6.0 Preview 2.0
VisualStudio.15.Preview/15.6.0-pre.2.0+27309.0

**Comment by rchiodo** [comment]
You should enter this request through Visual studio Report a problem, but I can comment on it here. 
We require our own custom version of CMake at the moment. This won't be supported until we can get all of the functionality we need in this branch into the mainline CMake, and then we'll require a specific version or higher.
