### ISSUE TITLE
Parameter name: pathValue cannot be null.

### ISSUE THREAD

**Issue by jensreck** [microsoft/CMake#58]
on generating CMake cache (doesn't matter Linux / Windows) multiple errors occurs...
Parameter name: pathValue cannot be null.
and CMake generation stops with error. On second call some messages also occurs but generation finished and build is possible.

1st call
----------------------------------------------------
1> Starting CMake target info extraction ...
1> CMake server connection made.
1> Extracted includes paths.
1> Extracted CMake variables.
1> Extracted source files and headers.
1> Extracted global settings.
1> Extracted code model.
1> Extracted CTest info.
1> Collating data ...
1> Target info extraction done.
Value cannot be null.
Parameter name: pathValue cannot be null.
Parameter name: pathValue cannot be null.
Parameter name: pathValue cannot be null.
Parameter name: pathValue cannot be null.
Parameter name: pathValue cannot be null.
Parameter name: pathValue cannot be null.
Parameter name: pathValue cannot be null.
Parameter name: pathValue cannot be null.
Parameter name: pathValue cannot be null.
Parameter name: pathValue cannot be null.
Parameter name: pathValue cannot be null.
Parameter name: pathValue cannot be null.
Parameter name: pathValue cannot be null.
Parameter name: pathValue cannot be null.
Parameter name: pathValue cannot be null.
Parameter name: path1> Command line: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\PREVIEW\PROFESSIONAL\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe  -G "Ninja" -DCMAKE_INSTALL_PREFIX:PATH="C:\Git\IcxFlatbuffers\public\bin\win-msvc-x64\Release"  -DCMAKE_CXX_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio/Preview/Professional/VC/Tools/MSVC/14.13.26127/bin/HostX64/x64/cl.exe"  -DCMAKE_C_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio/Preview/Professional/VC/Tools/MSVC/14.13.26127/bin/HostX64/x64/cl.exe" -DCMAKE_TOOLCHAIN_FILE=C:\Git\DevTools/tool_cmake/addons/modulesX/Platform/win-msvc-x64.cmake -DMSC_REQ_ADAPTER=1 -DCMAKE_BUILD_TYPE="Release" -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\PREVIEW\PROFESSIONAL\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" "C:\Git\IcxFlatbuffers"
1> Working directory: C:\Git\IcxFlatbuffers\private\generated\win-msvc-x64\Release
1> CMake generation canceled.

2nd call
-----------------------------------------------------------------------------------
1> Starting CMake target info extraction ...
1> CMake server connection made.
1> Extracted includes paths.
1> Extracted CMake variables.
1> Extracted source files and headers.
1> Extracted global settings.
1> Extracted code model.
1> Extracted CTest info.
1> Collating data ...
1> Target info extraction done.
Value cannot be null.
Parameter name: path

VS2017 infos
-----------------------------------------------------------------------------------
Microsoft Visual Studio Professional 2017 Preview
Version 15.6.0 Preview 5.0
VisualStudio.15.Preview/15.6.0-pre.5.0+27413.0
Microsoft .NET Framework
Version 4.7.02046

Installed Version: Professional

Visual C++ 2017   00369-60000-00001-AA634
Microsoft Visual C++ 2017

ASP.NET and Web Tools 2017   15.0.40213.0
ASP.NET and Web Tools 2017

C# Tools   2.7.0-beta3-62608-11. Commit Hash: 185540ca19bded1b976b61cc08973ca1135298d2
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

JavaScript Language Service   2.0
JavaScript Language Service

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

Visual Basic Tools   2.7.0-beta3-62608-11. Commit Hash: 185540ca19bded1b976b61cc08973ca1135298d2
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Linux Development   1.0.8
Visual C++ for Linux Development

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

**Comment by rchiodo** [comment]
Sorry this is a bug in VS, not in the CMake we ship. 

It's likely this issue here:
https://developercommunity.visualstudio.com/content/problem/196600/cmake-value-cannot-be-null-subpath.html

**Comment by jensreck** [comment]
so I forward this issue into this board?

**Comment by rchiodo** [comment]
Yes you can upvote the VS issue.

**Comment by rchiodo** [comment]
You can also try the workaround (as mentioned by the original poster)

> Deletion of .vs directory does fix it, so my guess is that database is corrupted.

**Comment by jensreck** [comment]
ok... some messages always occurs (at windows build) after deleting folder but no abort anymore...

Value cannot be null.
Parameter name: pathValue cannot be null.
Parameter name: path

thanks for your support!
