### ISSUE TITLE
Where to download version with windows10 support?

### ISSUE THREAD

**Issue by amerkoleci** [microsoft/CMake#7]
Where can I download CMake version with Windows 10 support?

Thank you

**Comment by wpbest** [comment]
Are you trying to support a Windows 10 Universal Windows Platform
Application? I'm not sure if they support that yet. I know they support
Windows 8.1 Store Applications. I have an example on my github.
https://github.com/wpbest/cmake-win-store-app You can start there?

**Comment by khouzam** [comment]
I have the binaries posted on my OneDrive. You can get them from: http://1drv.ms/1EgaGfv

**Comment by khouzam** [comment]
I have published a release with the changes that were submitted upstream to Kitware.

https://github.com/Microsoft/CMake/releases/tag/Win10RTM.v1

**Comment by amerkoleci** [comment]
Would be possible to have this stuff merged in official CMake version?
Anyway thank you

**Comment by drescherjm** [comment]
"the changes that were submitted upstream to Kitware." means that this is in progress.
