### ISSUE TITLE
CMake target Windows Phone Visual Studio 2015

### ISSUE THREAD

**Issue by ongamex** [microsoft/CMake#8]
I'm not sure if this is the right place to request this feature, but currently the official CMake is unable to generate VS Projects targeting Windows Phone for Visual Studio 2015.

**Comment by khouzam** [comment]
Yes, this is the right place. I'm currently in the process of issuing the pull request to Kitware to have the feature added.

For the time being please use our fork. Hopefully, it should be in their nightly soon.

**Comment by ongamex** [comment]
Thanks a lot for the quick answer!

Is there a pre-built version somewhere, or I have to build it myself?

**Comment by khouzam** [comment]
I've created a release for the changes that we have submitted to Kitware to be merged upstream.

https://github.com/Microsoft/CMake/releases/tag/Win10RTM.v1
