### ISSUE TITLE
CMAKE_SIZEOF_VOID_P not always declared

### ISSUE THREAD

**Issue by ohhmm** [microsoft/CMake#80]
CMAKE_SIZEOF_VOID_P is empty for sparc, tried niagara3 (Oracle Sparc T3)

**Comment by lukka** [comment]
@ohhmm thanks for the report. Is that a problem with upstream CMake? Or only with this fork of CMake?

**Comment by ohhmm** [comment]
Both

**Comment by lukka** [comment]
Could please you report this problem upstream CMake? Or in case you have a fix already please contribute it to upstream CMake.
FYI, we are not going to fix this specific problem in this fork.
