### ISSUE TITLE
add_test parsing - a mysterious __ArgsSep__ appears

### ISSUE THREAD

**Issue by peter-toft-greve** [microsoft/CMake#82]
I am using visual studio 2019 (latest build - with cmake 3.14.4)
When using 
cmd= python.exe;C:\Users\peter\proc.py;test_1;C:\Users\peter\foo.wav
add_test(NAME bla COMMAND ${cmd})
On Linux as well and in cmd.exe + powershell this makes the "bla" test run
  python C:\Users\peter\proc.py test_1 C:\Users\peter\foo.wav
 
However in visual studio 2019 I get and error 
Message: python.exe: can't open file 'C:\Users\peter\proc.py__ArgsSep__test_eq_1__ArgsSep__C:\Users\peter\foo.wav__ArgsSep': [Errno 2] No such file or directory

i.e. some odd voodoo replacement of the list spacer ";" into "_ _ ArgsSep _ _" goes really wrong (i.e. double underscore before and after the ArgsSep)

**Comment by peter-toft-greve** [comment]
I managed to make a demo of the problem - very small one... 
Requires MSVS 2019 + Python 3.7 (via https://www.python.org/downloads/windows/)
I have a demo.zip on my Google Drive only with source code and a README file
https://drive.google.com/open?id=1FHkH15WZOL65R_YSCRATj1TkUsRlXmfB

The build.bat runs in a powershell - from Visual Studio... burn burn burn

**Comment by peter-toft-greve** [comment]
also reported via https://developercommunity.visualstudio.com/content/problem/584817/ctest-parser-error-with-visual-studio-2019.html 
Dunno which channel is the best

**Comment by jgoshi** [comment]
The other channel that you reported is the correct one. I'm going to close this issue.
