### ISSUE TITLE
CSharp

### ISSUE THREAD

**Issue by ohhmm** [microsoft/CMake#94]
Please, consider adding CS language to Project command.

**Comment by jgoshi** [comment]
It seems like C# is supported by cmake:
https://stackoverflow.com/questions/2074144/generate-c-sharp-project-using-cmake

Also this repo is a fork of the Kitware cmake. Please open issues there where they are actively looked at.
https://gitlab.kitware.com/cmake/cmake

**Comment by ohhmm** [comment]
Thanks @jgoshi
